repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: hatch-fmt
        name: hatch fmt --check
        entry: hatch fmt
        language: system
        pass_filenames: false
    -   id: hatch-test
        name: hatch test
        entry: hatch test
        language: system
        pass_filenames: false